### ISSUE TITLE
"Application windows are expected to have a root view controller at the end of application launch"

### ISSUE THREAD

**Issue by benvium** [inamiy/YISplashScreen#4]
Hiya. I've tried using your default example with a storyboard project using the code:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  // show splash
  [YISplashScreen show];
  
  // simple fade out
  [YISplashScreen hide];
  
  return YES;
  }

.. on iOS 5.1.1 and iOS 6.0 I don't get the splash screen fade effect and the console logs out:

"Application windows are expected to have a root view controller at the end of application launch"

Any ideas?

EDIT: If I remove the two YISplashScreen lines I no longer get this message.

**Comment by inamiy** [comment]
Hi :)

It seems `[YISplashScreen hide]` works well for both iOS 5 and 6.
Maybe transition duration is too short for eyes, so try adjusting it by modifying source code and see the difference.

The issue regarding to "Application windows are expected to have a root view controller at the end of application launch" is
due to the original `window.rootViewController` being detached by the library for a short period of time,
mainly to prohibit executing any logic (especially CoreData) while transitioning splash screen.
This is a known issue but it's still OK for production release.

If you still don't like this warning, attaching dummy rootViewController might solve the problem.
I will also test this later, and if there is a progress, I will let you know.

**Comment by inamiy** [comment]
I committed version 1.0.0 just now.
API has been slightly changed, but it should solve all of your issues.

https://github.com/inamiy/YISplashScreen/tree/1.0.0

**Comment by benvium** [comment]
Great! Thanks, I'll give it a go on Monday.

**Comment by benvium** [comment]
Version 1.0.0 works perfectly for me, and I no longer get the warning. Thanks so much!

**Comment by inamiy** [comment]
You are welcome :)
